---
- name: Update all Raspberry Pi devices with Nala
  hosts: RASPI
  become: yes
  tasks:
 #   - name: Install Nala
 #     apt:
 #       name: nala
 #       state: present
 #     when: ansible_os_family == "Debian"

    - name: Update package list
      command: nala update
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages
      command: nala upgrade -y
      when: ansible_os_family == "Debian"
