---
- name: Remove unused docker images
  hosts: DOCKER
  become: true
  tasks:
    - name: Remove unused docker images
      shell: docker image prune -f
      register: result

    - name: Show results
      debug:
        var: result.stdout
