---
- name: Reboot Ubuntu servers if necessary
  hosts: VM
  become: true
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      shell: |
        echo "Server will be rebooted as it is necessary."
        shutdown -r now "Rebooting as required by system updates."
      when: reboot_required.stat.exists
      ignore_errors: true

    - name: Wait for server to come back online
      wait_for_connection:
        delay: 15
      when: reboot_required.stat.exists

